# Generated by Django 3.1.5 on 2021-01-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='question',
            new_name='table',
        ),
    ]
