# Generated by Django 3.1.5 on 2021-01-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210110_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='verif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
            ],
        ),
    ]
