# Generated by Django 3.1.5 on 2021-01-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_verif'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='email',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='table',
            name='phn',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
