# Generated by Django 3.1.5 on 2021-01-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210126_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='max_kg',
        ),
    ]
