# Generated by Django 3.1.5 on 2021-01-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_seller_max_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='table',
        ),
    ]
