# Generated by Django 3.1.5 on 2021-01-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_seller_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='photo',
            field=models.ImageField(default=0, upload_to='crops'),
        ),
    ]
