# Generated by Django 3.1.5 on 2021-01-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210128_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='photo',
            field=models.ImageField(default=0, upload_to='polls/media/image'),
        ),
    ]
