# Generated by Django 3.1.5 on 2021-02-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('priceperkg', models.CharField(max_length=200)),
            ],
        ),
    ]
